spring:
  jackson:
    time-zone: America/Toronto
  datasource:  
    url: jdbc:oracle:thin:@ctat7dbse1:1521:ccsdjx   
    username: pduser
    password: mappings
    driverClassName: oracle.jdbc.driver.OracleDriver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1 from dual
    maximum-pool-size: 25
    initial-size: 10
    minimum-idle: 0
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        ddl-auto: validate

server:
  port: 0
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    initialInstanceInfoReplicationIntervalSeconds: 40
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    
logging:
  level:
    ROOT: info
    org.springframework.web: info

           